# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.nevint.com:ios/nio-lib-repo.git'
source 'git@git.nevint.com:DOMOBILE-FeiDian/DOMOBILE-FeiDian-FDSpec.git' #DO-FDSpecs


platform:ios,'9.0'
inhibit_all_warnings!
use_frameworks!


target 'JSCoreDemo' do
  use_frameworks!
  pod "GCDWebServer", "~> 3.0"
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
